/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.net.sf.py4j.py4j)
    api(libs.fr.inria.corese.corese.core)
    api(libs.jakarta.activation.jakarta.activation.api)
    api(libs.info.picocli.picocli)
    testImplementation(libs.junit.junit)
}

group = "fr.inria.corese"
version = "4.5.0"
description = "corese-python"
java.sourceCompatibility = JavaVersion.VERSION_11

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
