name: Continuous Integration process
run-name: ${{ github.actor }} has launched CI process on ${{ github.ref_name }}
on:
  push:
    branches:
      - "develop"
      - "feature/add_tests"
  pull_request:
    branches:
      - "develop"

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  Continuous-Integration-Actions:
    runs-on: self-hosted

    steps:
      - name: Checkout of head
        id: ci-sources-checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        id: ci-java-setup
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies for ci process
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov setuptools wheel build

      - name: Build libray
        run: |
          env
          python -m build

      # - name: Need local jar files for the tests
      #   run: |
      #     ./gradlew clean shadowJar
      #     ./gradlew downloadCoreseCore

      - name: Test with pytest
        run: |
          pytest -v

      - name: Code coverage with pytest
        run: |
          pytest --cov

      - name: Final Step
        id: ci-final-step
        run: |
          echo "This job's status is ${{ job.status }}."
          echo "Created jar file(s):"
          find ./build -name '*.jar'
          echo "Created python package(s):"
          ls -l dist/*
