name: publish pycorese package on pypi.org
run-name: ${{ github.actor }} has launched CI process on ${{ github.ref_name }}
on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  Continuous-Integration-Actions:
    runs-on: self-hosted

    steps:
      - name: Checkout of head
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies for ci process
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov setuptools wheel build twine

      - name: Test with pytest
        run: |
          pytest -v

      - name: Code coverage with pytest
        run: |
          pytest --cov

      - name: Copy Jars
        run: |
          mkdir -p ./resources
          rm -rf ./resources/*
          cp ./build/libs/*.jar ./resources/

      - name: Build python libray
        run: |
          python -m build

      - name: Publish to pypi.org
        run: |
          TWINE_USERNAME="__token__" TWINE_PASSWORD=${{ secrets.PYPI_TOKEN }} twine upload dist/*

      - name: Final Step
        run: |
          echo "This job's status is ${{ job.status }}."
