name: publish pycorese package on pypi.org
run-name: ${{ github.actor }} has launched CI process on ${{ github.ref_name }}
on:
  push:
    branches:
#      - "main"
      - "feature/change_download_process"

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  Continuous-Integration-Actions:
    runs-on: self-hosted

    steps:
      - name: Checkout of head
        id: ci-sources-checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        id: ci-java-setup
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Gradle build
        id: ci-gradle-build
        run: |
          ./gradlew clean shadowJar
          ./gradlew downloadCoreseCore

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest setuptools wheel build twine
          # next line may be replaced by a requirements.txt file
          pip install pandas py4j jpype1
      - name: Test with pytest
        run: |
          pytest -v

      -name: Copy Jars
        run: |
          mkdir -p ./resources
          rm -rf ./resources/*
          cp ./build/libs/*.jar ./resources/

      - name: Build python libray
        run: |
          python -m build

      - name: Publish to pypi.org
        run: |
          pid=$$
          echo $PYPI_TOKEN > ./pypi.token.$pid

      - name: Final Step
        id: ci-final-step
        run: |
          echo "This job's status is ${{ job.status }}."
