# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/github_actions"
  pull_request:
    branches:
      - "main"
      - "develop"

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov setuptools wheel build
    - name: Test with pytest
      run: |
        pytest -v
    - name: Code coverage with pytest
      run: |
        pytest --cov
    - name: Build libray
      run: |
        python -m build
        ls -l dist/*
